### ISSUE TITLE
Remote Node get_balance throw Exception

### ISSUE THREAD

**Issue by deliugard** [ofek/bit#114]
`NetworkAPI.connect_to_node(user='use', password='password', host='ip_here')
print(NetworkAPI.get_balance('1NeJEFzY8PbVS9RvYPfDP93iqXxHjav791'))`

ERROR:
`Traceback (most recent call last):
  File "/tst.py", line 5, in <module>
    print(NetworkAPI.get_balance('35wc6hxyNUiwSnoB8xD2jktWEGHoWngrmu'))
  File "/venv/lib/python3.8/site-packages/bit/network/services.py", line 501, in get_balance
    return api_call(address)
  File "/venv/lib/python3.8/site-packages/bit/network/services.py", line 37, in get_balance
    b = Decimal(self.getreceivedbyaddress(address, 0))
  File "/venv/lib/python3.8/site-packages/bit/network/services.py", line 114, in __call__
    raise BitcoinNodeException("Error in RPC call: " + str(responseJSON["error"]))
bit.exceptions.BitcoinNodeException: Error in RPC call: {'code': -4, 'message': 'Address not found in wallet'}`

**Comment by teran-mckinney** [comment]
You need to have the wallet setup for it to work.

**Comment by deliugard** [comment]
already understood. Is there a ready-made function for adding an address to the "importaddress" list?

**Comment by teran-mckinney** [comment]
Looks like it: https://github.com/ofek/bit/blob/991d7f17bea00b718de0c5950a4637ef98fc16e3/docs/source/guide/remotenode.rst#adding-an-address-to-the-internal-wallet-of-a-node

Seems like the docs on https://ofek.dev/bit/ are out of date. @ofek, is there any way you could update those? I don't see the Remote Node page.

**Comment by deliugard** [comment]
Oh, nice docs. Thanks!

**Comment by teran-mckinney** [comment]
No problem!

**Comment by teran-mckinney** [comment]
Mind if I close this out? Or feel free to close it yourself if you feel it's ready.
