### ISSUE TITLE
Key object with brainwallet? [Question]

### ISSUE THREAD

**Issue by ateesdalejr** [ofek/bit#13]
The documentation [here](https://ofek.github.io/bit/guide/keys.html) mentions `from_hex` and a way to import from WIF. But is there a way to import a key from a brainwallet? e.g. `correct horse battery staple`? I've just taken a quick glance at the docs and was wondering if this is possible.

**Comment by ofek** [comment]
@ateesdalejr Not atm, sorry!

**Comment by ateesdalejr** [comment]
@ofek Is there a way I can get around this issue currently?

**Comment by ofek** [comment]
Nothing except for implementing that yourself I'm afraid.

**Comment by gbroiles** [comment]
this might be helpful:

from hashlib import sha256
from bit import Key

brainwallet = "correct horse battery staple"

address = "1C7zdTfnkzmr13HfA2vNm5SJYRK6nEKyq8" #from bitaddress.org
wif = "L3p8oAcQTtuokSCRHQ7i4MhjWc9zornvpJLfmg62sYpLRJF9woSu" #from bitaddress.org

key = Key.from_int((int(sha256(brainwallet.encode('utf-8')).hexdigest(),16)))
                
print("Brainwallet:", brainwallet)
print("Compressed address:", key.address)
print("Private key compressed WIF:",key.to_wif())
print("Private key:",key.to_hex())

print("Addresses are identical: ", (address == key.address))
print("WIF are identical:", (wif == key.to_wif()))

**Comment by ateesdalejr** [comment]
@gbroiles thanks for this! I'm not currently using this library at the moment but this is exactly what I needed.
