### ISSUE TITLE
fetch the balance of a third-party address

### ISSUE THREAD

**Issue by Th0rgal** [ofek/bit#131]
Hello,

I'ld like to fetch unspents of a third-party bitcoin address (I know the address but not the private key). Is it possible with bit?
According to the doc, here is what I can do when I know the private key:
```python
key = PrivateKeyTestnet(wif)
key.get_unspents()
```
Is there a way to create a key object (in read only mode?) from the public address instead of a wif?

Thanks,
Thomas

**Comment by GauthamramRavichandran** [comment]
You could try this [https://ofek.dev/bit/dev/api.html#bit.network.NetworkAPI.get_balance](https://ofek.dev/bit/dev/api.html#bit.network.NetworkAPI.get_balance)
Args is just an address,

**Comment by Th0rgal** [comment]
Alright thank you!
