### ISSUE TITLE
Any transaction in mainnet with confirmations=-1?

### ISSUE THREAD

**Issue by Oe0k** [ofek/bit#137]
Hello.
Any key.get_unspents() return [Unspent(amount=1111111, confirmations=-1, ... ]

Testing on version 0.6.2, 0.7.1

How this fix?

**Comment by pedr0-fr** [comment]
Also noticed this... seems like Bitcore API is returning -1 for the number of confirmations. Blockchair API might have issues too (https://github.com/ofek/bit/issues/127#issuecomment-673568114).
