### ISSUE TITLE
Address Balance Query

### ISSUE THREAD

**Issue by Isaacdelly** [ofek/bit#14]
I'm having issues with the <a href="https://ofek.github.io/bit/guide/network.html#balance">Code Sample from the Documentation</a> on balance requests. 

Why does the code sample use the Testnet to get a balance of a wallet. Is there a "Mainnet" function to access the balance? I assume that the Testnet doesn't provide accurate transactions from the Blockchain, am I wrong?

Also is there a way to get the balance of an address without knowing the private key, which is also used in the code sample. Many other libraries use the wallet address as the argument to a getBalance function.  Does Bit have something similar?

Code Sample In Question: `key = PrivateKeyTestnet('cU6s7jckL3bZUUkb3Q2CD9vNu8F1o58K5R5a3JFtidoccMbhEGKZ')`

Thanks in advance

**Comment by ofek** [comment]
https://ofek.github.io/bit/guide/keys.html#types

https://ofek.github.io/bit/guide/advanced.html#offline-transactions
