### ISSUE TITLE
Retour d'argent

### ISSUE THREAD

**Issue by Josianne53** [ofek/bit#149]
Bonjour,
Je me suis fait voler mes bitcoins j'ai pour 2821$ de bitcoins et je ne les ai jamais reçu. Mon adresse pour me les renvoyer es:
bc1qqz7787cfshyzhek5v6du9c7t9ek40ptnxwg0wa
Veuillez svp procéder au remboursement.

Merci
Johanne Rioux

**Comment by DrMartiner** [comment]
> Bonjour,
> Je me suis fait voler mes bitcoins j'ai pour 2821$ de bitcoins et je ne les ai jamais reçu. Mon adresse pour me les renvoyer es:
> bc1qqz7787cfshyzhek5v6du9c7t9ek40ptnxwg0wa
> Veuillez svp procéder au remboursement.
> 
> Merci
> Johanne Rioux

Hello,

I have a tool which allows to track a bitcoin transaction and build a graph of transaction base on graph DB. Can it help to solve the problem?

Best regards

**Comment by Josianne53** [comment]
ou je vais pour çà? Est-ce que je pourrai récupérer mes bitcoins?

**Comment by DrMartiner** [comment]
I don't know man, but u can track your btc. To get back your btc u need make an investigation and make a report to police. I don't know right way to make a conversation with police, but I know how to track btc...

**Comment by ofek** [comment]
This doesn't seem to be related to `bit`. @DrMartiner Thanks for helping though!
