### ISSUE TITLE
The fee rate seems quite wrong.

### ISSUE THREAD

**Issue by bombs-kim** [ofek/bit#152]
This library relies on `https://bitcoinfees.earn.com/api/v1/fees/recommended` for fee rate.
According to this, hourFee is 88 (satoshi/byte) at the moment. This number is based on 
`https://bitcoinfees.earn.com/api/v1/fees/list`

However, according to this `https://bitinfocharts.com/comparison/bitcoin-transactionfees.html#3y` the average satoshi/byte is 13 now. I suspect, `bitcoinfees.earn.com`'s information is unambiguously misleading.

Please also take a look at 
`https://api.blockchain.info/mempool/fees`
`https://api.blockchair.com/bitcoin/stats`

As a side note, the chart `https://bitcoinfees.earn.com/` also seems wrong, too.

**Comment by NateNate60** [comment]
I started a PR to change the fee provider to Mempool.space. Hopefully, it gets merged, because bitcoinfees.earn.com is usually woefully wrong, often not even in the same order of magnitude.
