### ISSUE TITLE
Implement BIP143 support?

### ISSUE THREAD

**Issue by teran-mckinney** [ofek/bit#16]
Required for #9 and might be a good step forward. You seem to already use compressed addresses by default.

Is this something you're interseted in doing? I'm already in way over my head trying to add Bitcoin Cash support to walkingliberty. pybitcoin doesn't have compressed public addresses nor BIP-143. electrum has BIP-143 but using that codebase looks like a nightmare.

Thank you!

**Comment by bjarnemagnussen** [comment]
I am working on implementing Segwit to Bit which uses BIP 143. Hopefully I can make a pull request soon. Maybe this will include some useful code that you can use, but don't expect the pull request to be merged immediately since it adds a lot of new code lines.

**Comment by bjarnemagnussen** [comment]
I have just created a preliminary branch in my repo which uses BIP-143 signature verification for Segwit functionality:
https://github.com/bjarnemagnussen/bit/commit/a3613640339ccca133550de329d7b4ac0470d407#diff-343cb9c183b69e67b2df6d3a57facd78R437

**Comment by expired-brain** [comment]
Great job bjarnemagnussen. Guys have you any idea to add other altcoin? 
That would be really useful.

**Comment by teran-mckinney** [comment]
@expired-brain, bit would need a lot of rewriting to support that. At this time, your best luck if if you fork off with another altcoin like how I did with bitcash. bit is a great base for other libraries, but it may get very tricky to support others all in one.

**Comment by bjarnemagnussen** [comment]
Fixed with commit 78d1ed9a3209fe8334399a498b0176e3bac5c1cb
