### ISSUE TITLE
Pay to scripthash

### ISSUE THREAD

**Issue by teran-mckinney** [ofek/bit#23]
I have no experience with paying to scripthashes except when it's worked automagically for me before.

In #12 it looks like the initial workins of P2SH are being added. I'm not sure how straight forward P2SH is.

But... for the time being shouldn't we throw an exception if we try to `send()` to an address that does not begin with 1? Are there any sideeffects to doing so?

I think I just lost a fair bit of coin not reviewing this properly. Hopefully if we add in an exception we can keep others from doing the same.

**Comment by bjarnemagnussen** [comment]
In the current master-branch it would definately make sense to add an exception if trying to send any address that does not start with a 1 (i.e. to a non-P2PKH address). But regarding my branch that is a work-in-progress adding P2SH functionality, sending to a P2SH address (starting with a 3) would work, but there is/was a bug. 

See here to read about the bug: 
https://github.com/ofek/bit/pull/12/files/a81726e03230f63ce7428a941cbda6111cd4816e#diff-343cb9c183b69e67b2df6d3a57facd78L140

and here to see a simple fix: 
https://github.com/bjarnemagnussen/bit/blob/7dfdf61e8e5a4136e811d1269290f6b310f1ed2b/bit/transaction.py#L248

**Comment by teran-mckinney** [comment]
Thank you! I'll try to write that in for both bit and bitcash, with test cases. May take me a couple days.
