### ISSUE TITLE
Starting Bit error: ImportError

### ISSUE THREAD

**Issue by gtaussie** [ofek/bit#25]
Hi, I am using Python3.6, and am having trouble starting with bit. I am running 3.6 inside a virtualenv, but get the following error:

> from bit import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/.../lib/python3.6/site-packages/bit/__init__.py", line 1, in <module>
    from bit.format import verify_sig
  File "/Users/.../lib/python3.6/site-packages/bit/format.py", line 1, in <module>
    from coincurve import verify_signature as _vs
  File "/Users/.../lib/python3.6/site-packages/coincurve/__init__.py", line 1, in <module>
    from coincurve.context import GLOBAL_CONTEXT, Context
  File "/Users/.../lib/python3.6/site-packages/coincurve/context.py", line 4, in <module>
    from coincurve.flags import CONTEXT_ALL, CONTEXT_FLAGS
  File "/Users/.../lib/python3.6/site-packages/coincurve/flags.py", line 1, in <module>
    from ._libsecp256k1 import lib
ImportError: dlopen(/Users/.../lib/python3.6/site-packages/coincurve/_libsecp256k1.cpython-36m-darwin.so, 2): Library not loaded: /usr/local/opt/gmp/lib/libgmp.10.dylib
  Referenced from: /Users/.../lib/python3.6/site-packages/coincurve/_libsecp256k1.cpython-36m-darwin.so
  Reason: image not found

I have checked that my path, and that i'm running python3.6:
>>> print(sys.path)
['', '/Users/.../lib/python36.zip', '/Users/.../lib/python3.6', '/Users/.../lib/python3.6/lib-dynload', '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6', '/Users/.../lib/python3.6/site-packages']

Any help would be appreciated!

**Comment by ofek** [comment]
How did you install bit?

**Comment by teran-mckinney** [comment]
I've never used bit on OS X before. Does `/usr/local/opt/gmp/lib/libgmp.10.dylib`exist? If not, may have to install gmp. There's some package manager for OS X that I've forgotten the name of.

This seems like maybe it was a binary wheel install of sorts although I'm not that familiar with how Python installs look on the disk and behave via pip.

**Comment by gtaussie** [comment]
@ofek It was installed via pip3. first under the local system, then also tried inside a virtualenv

i am running the command <from bit import *> after running 'python3' 

@teran-mckinney no, that directory does not exist on my system. only /usr/local/bin/. No other folders exist at the .../local/ level (apart from /local/bin)

**Comment by ofek** [comment]
Can you please try installing in a fresh virtual env and show all output?

**Comment by gtaussie** [comment]
Hi ofek, i have created a fresh virtual env, and have pasted the output here: https://pastebin.com/k8jaKxmu
