### ISSUE TITLE
Generate address with text

### ISSUE THREAD

**Issue by xcbtrader** [ofek/bit#29]
Hello.
Is possible to generate address with text ?
for exemple:

k = Key('Hello this is my text')
print(k.address)

**Comment by ofek** [comment]
Yes but this is insecure.

```
Ofek@Ofek-PC ~ $ from bit import Key                            
Ofek@Ofek-PC ~ $ k = Key.from_bytes(b'Hello this is my text')   
Ofek@Ofek-PC ~ $ k.address                                      
'1P5Kafexb6c3DnARXY2Nv7QJh3awbJrHGM'                            
```

**Comment by xcbtrader** [comment]
If, the text is in a variable??

**Comment by ofek** [comment]
`k = Key.from_bytes(text1.encode())`

**Comment by xcbtrader** [comment]
Hello.
I test your solution but in the past i test bitcoin library vbuterin, and if i compare de results, don't work

def create_addr_text(word):	
	key = Key.from_bytes(word.encode())
	wif = key.to_wif()
	addr= key.address
	return addr, wif
	
def create_addr_word(word):
	priv = sha256(word)
	pub = privtopub(priv)
	addr = pubtoaddr(pub)
	return addr

what's the diference????
