### ISSUE TITLE
Bug with send(combine=False)

### ISSUE THREAD

**Issue by teran-mckinney** [ofek/bit#30]
I think there's some weird behavior here.

https://blockchain.info/tx/6519c1977bf0863aed1b70caeaeb521c32fab43e5fd663c310f09cdee63d0ad6?show_adv=true

The fee was super high but I think that was a sideeffect of the main bug.

**Comment by teran-mckinney** [comment]
The issue is that we are estimating fees based on all the unspents, whether we use them or not. Then the fee is so big we have to add unspents to cover it.

**Comment by teran-mckinney** [comment]
This is what I have drafted so far as a test to catch this. I think it explains it better.

```
diff --git a/tests/test_transaction.py b/tests/test_transaction.py
index 72db025..79457ee 100644
--- a/tests/test_transaction.py
+++ b/tests/test_transaction.py
@@ -173,6 +173,34 @@ class TestSanitizeTxData:
         assert outputs[1][0] == RETURN_ADDRESS
         assert outputs[1][1] == 1000
 
+    def test_no_combine_with_fee(self):
+        """
+        Verify that unused unspents do not increase fee.
+        """
+        unspents_single = [Unspent(5000, 0, '', '', 0)]
+        unspents_original = [Unspent(5000, 0, '', '', 0),
+                             Unspent(5000, 0, '', '', 0),
+                             Unspent(5000, 0, '', '', 0)]
+        outputs_original = [(BITCOIN_CASHADDRESS_TEST_COMPRESSED, 1000, 'satoshi')]
+
+        unspents, outputs = sanitize_tx_data(
+            unspents_original, outputs_original, fee=1, leftover=RETURN_ADDRESS,
+            combine=False, message=None
+        )
+
+        unspents_single, outputs_single = sanitize_tx_data(
+            unspents_single, outputs_original, fee=1, leftover=RETURN_ADDRESS,
+            combine=False, message=None
+        )
+
+        assert unspents == [Unspent(5000, 0, '', '', 0)]
+        assert unspents_single == [Unspent(5000, 0, '', '', 0)]
+        assert len(outputs) == 2
+        assert len(outputs_single) == 2
+        assert outputs[1][0] == RETURN_ADDRESS
+        assert outputs_single[1][0] == RETURN_ADDRESS
+        assert outputs[1][1] == outputs_single[1][1]
+
     def test_no_combine_insufficient_funds(self):
         unspents_original = [Unspent(1000, 0, '', '', 0),
                              Unspent(1000, 0, '', '', 0)]
```

Of course, this fails currently.

**Comment by ofek** [comment]
Thanks! Let me know what you think of https://github.com/ofek/bit/pull/31

**Comment by teran-mckinney** [comment]
So we are sorting by small inputs. If we move the fee calculation later, it only works if the fee is small enough to fit in the remainder of the last input.

I think combine=False is quite complicated to implement correctly. You also run a risk if you start to do a running tally of the fee (comparing it while adding inputs) you may end up adding inputs that cost more fees than they pay. But that may be the easiest fix overall.

**Comment by ofek** [comment]
Ah, I see. Yes this is tricky :slightly_frowning_face:

**Comment by ofek** [comment]
I sent you an invite btw

**Comment by teran-mckinney** [comment]
I accepted it, thank you!

Interesting fix you have there. It acts more like combine=True.

I am working on one right now that also includes a test just for this. Let me open it in a few minutes and we can compare.

**Comment by teran-mckinney** [comment]
The other issue with the above transaction was that the connection to the bitcoin fee API failed. In #32 I am adding some logging to hopefully let the application know that it is reverting to the default fee.

Please let me know what you think.

Thanks!
