### ISSUE TITLE
how to get the public key hash ,and create multiple address using primary key?

### ISSUE THREAD

**Issue by kingctan** [ofek/bit#35]
how to get the public key hash ,and create multiple address using primary key?

**Comment by teran-mckinney** [comment]
Every address is based on a different public key hash. What you want to do is find a way to derive multiple addresses from a single private key. There are various methods, I would look through HD deterministic wallets. There's documentation on the various BIPs for that.

It can be as simple as saying: `private_key = sha256(private_key + str(address_nonce)`, in pseudo-Python code. Do a for loop, going through as many addresses as you want with address_nonce.

**Comment by kingctan** [comment]
thanks a lot. @teran-mckinney and,
I want to know how to get the balance about the each address ?
any code example please!
Thanks.

**Comment by teran-mckinney** [comment]
Here's a basic example:

```
from bit import Key

for key in generate_keys_from_master_key('your key'):
    bit_key = Key(key)
    print(bit_key.get_balance('usd'))
```

**Comment by kingctan** [comment]
@teran-mckinney 
the code get balance using private key, not using address. ^_^

I have found another way to do it using pywallet.

Thanks.
