### ISSUE TITLE
How do you generate a public address?

### ISSUE THREAD

**Issue by linux-mining** [ofek/bit#36]
I'm not sure where else to ask, but I can't seem to generate a public address(for sending transactions).
According to your wiki after generating a private key via key = Key() I should be able to use the address attribute. but key.address give back the private key again and key.public_key generates something unusable (at least by a novice).

What am I doing wrong?

**Comment by ofek** [comment]
Can you paste some output?

**Comment by ofek** [comment]
https://docs.python.org/3/tutorial/interpreter.html
https://github.com/ofek/bit/blob/4568b1df1f4cc1dc4a8e4058f749c6a1f42fb5b2/bit/wallet.py#L403

**Comment by linux-mining** [comment]
Python 3.5.1 (default, Oct 21 2016, 21:37:19) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.

?

**Comment by ofek** [comment]
Everything is working normally. Experiment by doing `type(stuff)`.

**Comment by linux-mining** [comment]
So how to you generate a public key to share with others?

**Comment by ofek** [comment]
That's your address.

**Comment by linux-mining** [comment]
Its a bit concerning that the public key is equal to the private key. I guess I'm getting gas lighted at this point for missing something...

**Comment by ofek** [comment]
It's not equal. I'd strongly advise getting a better grasp of Python before trying anything money-related!

**Comment by linux-mining** [comment]
Sorry to bother you, I will continue to use bitcoin core to generate key pairs, its just a bit slow. I can't seem to get your program to output both of them. 

Good luck on the project.

**Comment by ofek** [comment]
```python
Python 3.6.1 | packaged by conda-forge | (default, May 23 2017, 14:21:39) [MSC v
.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from bit import Key
>>> key = Key()
>>> key
<PrivateKey: 16XwWCi4egGL2sAnBAEik2eb8TXyfMjBZR>
>>> key.address
'16XwWCi4egGL2sAnBAEik2eb8TXyfMjBZR'
>>> type(key)
<class 'bit.wallet.PrivateKey'>
>>> type(key.address)
<class 'str'>
```

Does it make sense now?

**Comment by linux-mining** [comment]
Yes I understand one is apparently a custom class you designed vs a string literal. My interest was more a practical one. I simply needed to generate key pairs.  I don't expect you to help my ignorance of bitcoin, it is just not clear to me how to generate these key pairs in the format that most end users expect to use.

Bitcoin core's daemon does exactly what I needed. It will spit out a private/public key pair in what ever format seems to be desired by end users.  Issue is solved. 

Thanks for your time.

**Comment by ofek** [comment]
Did you see this? https://ofek.github.io/bit/guide/keys.html#public-key

**Comment by linux-mining** [comment]
Yes of course I saw that. My issue is one of my own ignorance believe me. I simply couldn't get a private / public key pair in a format that matched what was specified. 

Again, bitcoin core does this by default without any complications via the command line. Issue is resolved. 

You can mark as solved. Thanks again.

**Comment by ofek** [comment]
Okay, take care!

**Comment by linux-mining** [comment]
A kind sole pointed out to me what I was missing is the export call to generate the private key in the format I was expecting. Thanks kind sole.
