### ISSUE TITLE
Questions about balance

### ISSUE THREAD

**Issue by albertocastillo2001** [ofek/bit#38]
Hello

How is the get_balance informatin retrieved? Is it getting from blobkchain.info? Is there a limit on how many times in a row you can use it?
It has returned 0 satoshis on the private keys I tried even when the computer was disconnected from the network.
Also, is it possible to get the balance of a public key/address instead of a private key?

Thanks

**Comment by albertocastillo2001** [comment]
I noticed that key.balance will display 0 if the method key.get_balance() hasn't been run yet. Is this a normal behavior?
Is there a limit on how many times you can use this? Where is this information retrieved from?

Thanks

**Comment by teran-mckinney** [comment]
You need to call get_unspents() off the object to update the balance object. I think it may be more intuitive to have it set to None, or something like that, before get_unspents() is called. Balance is calculated through unspents, not through a balance call to the APIs.

blockchain.info, some Australian service, and another are used. There are limits, you'll want to read the service.py information, there's some info on ratelimits in the comments (may not be current). If one fails it'll try another.

**Comment by albertocastillo2001** [comment]
Thank you, apparently get_balance() shows the balance at least on testnet and updates the key.balance property fine, should I need to use get_unspents()?

So what error does get_balance() return in case it cannot return the balance? does it show an error or just display 0?

Thanks

**Comment by teran-mckinney** [comment]
Ah, get_balance() does work, yes. Either is fine. get_balance() will call get_unspents() every time.

If it can't return the balance it should raise an exception.

**Comment by albertocastillo2001** [comment]
Thank you!

**Comment by teran-mckinney** [comment]
You're welcome! Mind if I close this out?

**Comment by albertocastillo2001** [comment]
Yep, you can close it, thanks!
