### ISSUE TITLE
Testnet transfers fail when there are clearly unspents available

### ISSUE THREAD

**Issue by nirmalthacker** [ofek/bit#39]
Hi,

Great library, thanks for building it!

I was able to get to speed rather quickly and could move testnet coins around but I noticed that very often I have to wait a while for create_transaction() or send() to return without errors. In some cases I had 8 confirmations on a testnet wallet after getting some coins from a faucet and trying to move them to destinations also generated by this same library. The error I usually hit : 

```
~/anaconda2/envs/foo/lib/python3.6/site-packages/bit/transaction.py in sanitize_tx_data(unspents, outputs, fee, leftover, combine, message, compressed)
     93 
     94     if not unspents:
---> 95         raise ValueError('Transactions must have at least one unspent.')
     96 

```

However calling get_unspents() clearly shows Unspents and confirmations. What's the reason for this error?

**Comment by nirmalthacker** [comment]
I got around this error by passing the value for function argument unspent, so:
```

key.create_transaction(outputs,unspents=key.get_unspents())
key.send(outputs,unsepnts=key.get_unspents())
```

This works and the transactions are transmitted to Testnet. But without setting these, I continue to hit the above Exception

**Comment by mrx23dot** [comment]
This is still in an issue, when I follow the manual to transfer everything out:
key.send([], leftover="addr...")

I get
    raise ValueError('Transactions must have at least one unspent.')
Is it really mandatory to specify the unspent?

**Comment by teran-mckinney** [comment]
I've never needed to specify unspents. You have to call `get_unspents()` to load them, you don't have to actually pass them.

**Comment by mrx23dot** [comment]
The example also fails because of this on the main page and in the manual:
https://github.com/sporestack/bitcash

**Comment by teran-mckinney** [comment]
`get_balance()` calls `get_unspents()`. Are you sure the example isn't working?

**Comment by mrx23dot** [comment]
Yeah, just tested get_balance() or get_unspents() is required before send().

It is different from InsufficientFunds, which is good.
bitcash.exceptions.InsufficientFunds: Balance 1000 is less than 422874 (including fee).

Automatic calling of either (if none were called before) would eliminate these gotchas.

Btw, I love the library, integrating it into a payment system, cheers!

**Comment by ofek** [comment]
> Automatic calling of either (if none were called before) would eliminate these gotchas.

Good idea
