### ISSUE TITLE
pycoin timings using pure Python code only, which is much slower than OpenSSL version

### ISSUE THREAD

**Issue by richardkiss** [ofek/bit#4]
I'm the author of pycoin.

The page https://github.com/ofek/bit/blob/master/docs/source/guide/intro.rst show shows pycoin as being very slow generating sec blobs. This can be sped up very significantly by setting the environment variable ```PYCOIN_NATIVE=openssl``` which will use OpenSSL for two slow functions. See also the "Too slow?" section at https://github.com/richardkiss/pycoin/blob/master/README.md

**Comment by ofek** [comment]
Thanks!

I just tried that but it doesn't appear to work on Windows. Is that correct? If so, I'll try in a VM tomorrow.

**Comment by richardkiss** [comment]
No, I've never tried it on Windows. If it fails, it's likely due to a ctypes library issue (and you probably know how to solve better than I do!). Also see https://github.com/richardkiss/pycoin/pull/177/files

It does work on Mac OS X, Linux, and I believe FreeBSD.

If you need help getting it working, I'll do what I can (although I don't have convenient access to a Windows box).

**Comment by ofek** [comment]
I added a big note [https://ofek.github.io/bit/guide/intro.html#why-bit](url).

Thanks again for bringing this to my attention!

**Comment by richardkiss** [comment]
Great, thank you!

**Comment by richardkiss** [comment]
Your docs look great... I hope you wouldn't mind if I borrowed the docs framework for pycoin.

**Comment by ofek** [comment]
I myself got the template from [https://github.com/kennethreitz/requests](https://github.com/kennethreitz/requests), so no problem :)
