### ISSUE TITLE
Advanced: Hex to WIF unable to import

### ISSUE THREAD

**Issue by albertocastillo2001** [ofek/bit#40]
Hello

I need to find the uncompressed and compressed WIFs from a HEX key. I managed to get the compressed format using .from_hex() succesfully

In the advanced section of the documentation there's a section about Hex to WIF, I am unable to import that module and unable to get an uncompressed WIF
https://ofek.github.io/bit/guide/advanced.html

Thank you.

**Comment by teran-mckinney** [comment]
What exactly isn't working? The example should work verbatim from what I can tell.

Ideally, we should have Key(compressed=False), though. That would be better here.

**Comment by albertocastillo2001** [comment]
Sorry

For example trying to import hex_to_wif will already fail
`from bit.format import hex_to_wif`

`Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    from bit.format import hex_to_wif
ImportError: cannot import name 'hex_to_wif' from 'bit.format' (C:\Users\alcastil\AppData\Local\Programs\Python\Python37-32\lib\site-packages\bit\format.py)`

**Comment by AndZhig** [comment]
At me too does not work on win 10.

**from bit import * 
key = Key(compressed=False)
print(key)**

speaks 

...line 8, in <module>
    key = Key(compressed=False)
TypeError: __init__() got an unexpected keyword argument 'compressed'

**Comment by teran-mckinney** [comment]
`Key(compressed=False)` doesn't exist, I was saying it would be nice if it did.

**Comment by bjarnemagnussen** [comment]
Fixed with 713f13d0203c53073b72ac134fc693a2e9b44627
