### ISSUE TITLE
Uncompressed public keys

### ISSUE THREAD

**Issue by xcbtrader** [ofek/bit#52]
Hello
I need to create uncompressed public keys whith text.
For compressed Keys i use:
	key = Key.from_int(int(sh.sha256(word.encode('utf-8')).hexdigest(),16))
	wif = key.to_wif()
	addr= key.address
works fine, but i need the same with uncompressed.
It's possible ??

**Comment by teran-mckinney** [comment]
I think you have to convert to WIF and then import a WIF that has compression turned off. Unfortunately, may not be easy other than a modification to the bit code.

**Comment by xcbtrader** [comment]
Sorry.
How do I do it?

**Comment by bjarnemagnussen** [comment]
I just saw your question now.

One workaround with lots of converting would be the following:
```
from bit import Key
from bit.format import wif_to_bytes, bytes_to_wif
key = Key.from_int(int(sh.sha256(word.encode('utf-8')).hexdigest(),16))
wif = key.to_wif()

# Make wif to bytes:
wif_bytes = wif_to_bytes(wif)
# Returns: (private_point, compressed, version)

# Change wif-tuple to uncompressed:
# Note: what wif_to_bytes returns is a tuple that is not in the same order which bytes_to_wif takes as argument!
wif_bytes_uncompressed = (wif_bytes[0], wif_bytes[2], False)
wif_uncompressed = bytes_to_wif(*wif_bytes_uncompressed)

# Import uncompressed wif:
key_uncompressed = Key(wif_uncompressed)
addr_uncompressed = key_uncompressed.address
```

**Comment by xcbtrader** [comment]
Thanks!!!!
Work Fine..

**Comment by Miri0070** [comment]
Hello!
did any one a generator with cuda?
