### ISSUE TITLE
Class MultiSig creates different contracts depending on the ordering of public keys

### ISSUE THREAD

**Issue by bjarnemagnussen** [ofek/bit#55]
Currently the `MultiSig` class behaves like the raw Bitcoin protocol by creating a multisignature contract ordering the public keys in the Script exactly as they were used as arguments in the initialization of `MultiSig`.

For Bit I think it would make much more sense to use lexicographical ordering of the public keys, so that it does not matter in which order the public keys are presented when initializing the `MultiSig` class (see answer to https://bitcoin.stackexchange.com/questions/39370/how-to-create-the-same-2-of-3-multisig-adresses-as-electrums-multisig-wallets). 

I regret not having thought of that from the beginning. Following the implementation of P2SH multisignature, Bit has grown to a new release number and forcing lexicographical ordering may break currently used multisignature contracts created with the class `MultiSig`.

For simplicity of use in Bit I suggest to change the default behaviour to use lexicographical ordering, but allowing a flag to be set that disables this ordering. A code change to allow for this would be quite straight forward. 

Are there any reasons against it?

**Comment by teran-mckinney** [comment]
I can't think of any. This seems like a good idea to me.
