### ISSUE TITLE
Testnet wallet is drained

### ISSUE THREAD

**Issue by bjarnemagnussen** [ofek/bit#60]
Currently the testnet wallet `WALLET_FORMAT_TEST` is drained (see last Travis build report). Since we return testnet coins to the address `n2eMqTT929pb1RDNuqEnxdaLau1rxy3efi` belonging to the faucet `tpfaucet.appspot.com`, I wanted to request new testnet coins from them.

However it appears that the faucet is offline (the captcha hasn't been working for some time). So maybe we should switch to another faucet and also use that new faucet's address to return testnet coins?

**Comment by teran-mckinney** [comment]
Seems like we have these two to fill up, right?

https://live.blockcypher.com/btc-testnet/address/mtrNwJxS1VyHYn3qBY1Qfsm3K3kh1mGRMS/

https://live.blockcypher.com/btc-testnet/address/muUFbvTKDEokGTVUjScMhw1QF2rtv5hxCz/

For the time being, I just used https://testnet-faucet.mempool.co/ to send 0.01 to both. Won't last long, maybe not for even one test, but may be something.

Would be nice to send to an address that sends it right back. Maybe we could make a service like that for testnet.

**Comment by ofek** [comment]
Now that we have a faucet working again tests are passing and I've released `0.5.0`!!! Also we now "officially" support Python 3.7 😄 

You guys rock

**Comment by teran-mckinney** [comment]
Awesome, thank you!
