### ISSUE TITLE
Local node support

### ISSUE THREAD

**Issue by johndoe123445** [ofek/bit#62]
Hi,

This seems to be the only sanest python bitcoin library. Truely, great work there.

I would love to use this library but unfortunately local nodes are not supported.

Do you have any timeline to support the local nodes? 

Do you need funding or donation?

Please, let me know.

**Comment by teran-mckinney** [comment]
Thank you for the kind words. @ofek and @bjarnemagnussen have done terrific work, I've only done small and odd patches here and there.

I haven't heard of any timeline for local node support, but I agree that it would be very useful. I don't believe any of the bit work has been paid before.

I think it should be possible to integrate and would make sense. I'm going to be busy for a while but there's a slim chance I might be able to work on something like this in a month or so. @ofek or @bjarnemagnussen would likely be more qualified. I think it would be involved but not terribly difficult.

**Comment by bjarnemagnussen** [comment]
Hi @johndoe123445, thanks for you words! With local node support, do you mean connecting to your own node for Bitcoin network API communication, such as retrieving transactions, etc.? 

I have been thinking about this some time before, and one way could be to communicate with the Electrum Stratum network, or by using Bitcoin Core's RPC.
@ofek and @teran-mckinney: What do you think about it? Which way to support it do you think is prefered?

**Comment by teran-mckinney** [comment]
Personally, I would lean towards Bitcoin Core RPC first, and anything else after. It should be configurable for localhost or any other host string and port.

I think it's a good starting point and other coin daemons emulate the API.

**Comment by johndoe123445** [comment]
@bjarnemagnussen I think Bitcoin core RPC will be more better.

**Comment by bjarnemagnussen** [comment]
Thanks for your inputs!

**Comment by johndoe123445** [comment]
How are other apis different from bitcoin core rpc?

Is creating your own api documented? network/services.py seems to be uh well... hacky.

**Comment by MatthiasLohr** [comment]
Would really like this feature, too!

**Comment by parasjain** [comment]
Hi guys, this is the most sane library present out there. It would be really helpful feature. Is there any plan as to when will this feature be implemented?

**Comment by teran-mckinney** [comment]
Adding APIs isn't documented and we all agree it would be a good feature. Just a matter of time to implement it.

Might need some better toggling for only using certain APIs and being able to pass parameters for the RPC API.

And yes, other APIs are very different from the RPC API.

**Comment by bjarnemagnussen** [comment]
Fixed with #76
