### ISSUE TITLE
import bit failure on Mac OS Sierra 10.12.5 (16F73)

### ISSUE THREAD

**Issue by zeropoid** [ofek/bit#7]
I was trying to import bit, right after installing it and getting this:
![hrnxsf6mtkwx_tysb9mkiw](https://user-images.githubusercontent.com/8404207/29253522-f39c4980-8087-11e7-8351-48702e6b3eef.png)

What could be a reason for this? and how to solve it?

**Comment by ofek** [comment]
Hello @zeropoid, thanks for your interest in Bit!

Unfortunately, Bit only supports Python 3.5+.  Please refer to http://docs.python-guide.org/en/latest/starting/install3/osx

**Comment by zeropoid** [comment]
Okey thank you!
