### ISSUE TITLE
MultiSig naming suggestion

### ISSUE THREAD

**Issue by omarrida** [ofek/bit#74]
Fantastic repo. When I first used this, I was confused by the naming of MultiSig. I assumed the class was a MultiSig wallet, but it actually represents a single member of the MultiSig wallet right?

Would you consider a PR renaming it to MultiSigMember, or can you think of a better name?

**Comment by bjarnemagnussen** [comment]
Thanks for your feedback! Unfortunately, Bit does not (yet) implement a "wallet" class. 

The `MultiSig` class is an (independent) instance of a Bitcoin multisignature contract, and therefore I don't think "member" would be a fitting name. It could have been named `MultiSigContract`, but I am afraid this would also lead to other confusions regarding "smart contracts", etc.

However, I will take your point into consideration and try to better explain it in Bit's documentation with a future commit.
