### ISSUE TITLE
How to send from multiple addresses to multiple addresses

### ISSUE THREAD

**Issue by ryanli1994** [ofek/bit#8]
If I want to send a multi-multi transaction like [this](https://blockchain.info/tx/1101e3b104cb78c808916f15540739bc98161a2dff29b811d49d2836d56aa580), but bit only supplies `create_transaction` method in the key.

I found that it can specify UTXOs (https://ofek.github.io/bit/guide/transactions.html#unspent), can I use this method to create a transaction from multiple addresses to multiple addresses?

**Comment by ofek** [comment]
Bit currently does not support P2SH transactions, sorry!

**Comment by ryanli1994** [comment]
@ofek It's okay, thanks for your efforts working on this great library 👍
