### ISSUE TITLE
Signing and verifying

### ISSUE THREAD

**Issue by nirmalthacker** [ofek/bit#87]
Hi

I'm looking for 2 features that existing popular wallets already offer:
1. Sign a message using private keys
2. Verify a message, given the message and signature

Is this possible? I dont see it in the documentation

**Comment by teran-mckinney** [comment]
Bit uses [coincurve](https://github.com/ofek/coincurve) which has signing and verification. It's just at a lower level.

**Comment by nirmalthacker** [comment]
Seems like I can use bit.verify_sig(signature, message, public_key) to do this ?

When I use a testnet public key I hit the error:

    raise ValueError('The public key could not be parsed or is invalid.')
ValueError: The public key could not be parsed or is invalid.

**Comment by teran-mckinney** [comment]
Do mainnet keys work as well? Are you entering an address or the hash of a public key?

I don't know a whole lot about signing and validating addresses, @ofek is more qualified here.

**Comment by nirmalthacker** [comment]
Mainnet keys also fail with the same error, but I think whats happening is that I'm using a public address and not public keys. Would you know how I can take a string public address and turn into a bytes public key using this library?

**Comment by teran-mckinney** [comment]
Sure, format.address_to_public_key_hash().

There's even a verify_sig() in bit/format.py, but still works with keys and not addresses.

**Comment by bjarnemagnussen** [comment]
It is not possible to extract the public key using `address_to_public_key_hash()` as it is will only return the *hash* of the public key. 

I am not very familiar with the Bitcoin message signing procedure, but I think together with the message and signature, you should also receive the public key for the address to verify the signature with. Additionally you must then verify that the hash160 of the public key matches the value of the Bitcoin address.

**Comment by nirmalthacker** [comment]
@bjarnemagnussen You're right about it returning the hash. I'm still not clear how one would verify a digital signature programmatically.

I'd like to do this outside of bitcoin transactions. Given the following: Arbitrary message, Signature, Public Address I'd like to verify that the owner of the public address signed the arbitrary message. 

This can be done, because I verified as below:
1. Generate Legacy and Segwit Bitcoin wallets with Electrum
2. Use Electrum to sign messages with the above private keys
3. Verify at Brain Wallet [https://brainwalletx.github.io/#verify] . The Legacy wallet verification works but Segwit does not and it could be that Segwit keys are not currently recognized by Brain wallet given its development has ceased.

Now, I'm looking to replicate this with Python

**Comment by teran-mckinney** [comment]
@bjarnemagnussen I was thinking it might be something like that. I don't think you can validate a Bitcoin signature until that address has made a TX and revealed its public key. The TX would have to be looked up to reveal the public key.

**Comment by ofek** [comment]
Talked it over with lead devs on libsecp256k1 and indeed this is impossible without a trial-and-error hack. I will come up with a snippet tonight.

**Comment by ofek** [comment]
I didn't have time, but will do over the weekend

**Comment by ofek** [comment]
Try this:

```python
from bit.format import public_key_to_address
from coincurve import PublicKey
from coincurve.ecdsa import der_to_cdata, serialize_compact
from coincurve.utils import int_to_bytes

def verify(sig, message, address):
    for rec_id in (0, 1, 2, 3):
        serialized_sig = serialize_compact(der_to_cdata(sig))
        serialized_recoverable_sig = serialized_sig + int_to_bytes(rec_id)
        pk = PublicKey.from_signature_and_message(serialized_recoverable_sig, message)
        match = public_key_to_address(pk.format()) or public_key_to_address(pk.format(compressed=False))
        if match:
            return True
    return False
```

**Comment by teran-mckinney** [comment]
Awesome, thank you! I will have to give that a try some time.

**Comment by nirmalthacker** [comment]
Hi @ofek , Thanks for the snippet but I can't get it to run. Running it with both Legacy and Segwit bitcoin wallets and passing bytes sig, bytes message, string address 

```
    serialized_sig = serialize_compact(der_to_cdata(sig))
  File "/Users/nirmal/miniconda3/envs/bitcoin/lib/python3.7/site-packages/coincurve/ecdsa.py", line 23, in der_to_cdata
    raise ValueError('The DER-encoded signature could not be parsed.')
ValueError: The DER-encoded signature could not be parsed.
```

**Comment by ofek** [comment]
@nirmalthacker Can you show sig? Either as hex or Python object printing

**Comment by nirmalthacker** [comment]
Signature in string (outputted by electrum): H7138LQS98boCgw5TQ860e9MDRyhu5XFe51r9uLAOqfrcwDHuuFxC5W2SVXSNv3X4foaJ5hPmHEw/4hJ/PXSsxQ=

Hex encoded: 
48373133384c51533938626f43677735545138363065394d44527968753558466535317239754c414f716672637744487575467843355732535658534e76335834666f614a3568506d4845772f34684a2f5058537378513d

**Comment by ofek** [comment]
Perhaps @teran-mckinney or @bjarnemagnussen can confirm but that doesn't look like a sig. Sigs should be between 68 and 71 characters (inclusive) but after base64 decoding that is 65

**Comment by bjarnemagnussen** [comment]
I am working on a small write-up to show how to use the `verify` function with Electrum's signature to verify the message and signature.

**Comment by bjarnemagnussen** [comment]
Alright, it is a little bit involved!

1) Transaction signing using Bitcoin Core's rule prepends the text with `"\x18Bitcoin Signed Message:\n" + compactSizeEncoding( len(message) )`, as explained on StackExchange[1].

2) The `verify` function from Ofek expects the signature to be in DER-encoded format[2]. But we can rewrite it to make use of the compact signature format directly from Electrums signature format.

3) Your decoding of the Electrum signature into hex is wrong, as it is base64 encoded and should result in:
`1fbd77f0b412f7c6e80a0c394d0f3ad1ef4c0d1ca1bb95c57b9d6bf6e2c03aa7eb7300c7bae1710b95b64955d236fdd7e1fa1a27984f987130ff8849fcf5d2b314`

### Let's make an example
* Address: `13bq7o1ybfnG83wSfyinuWvLrVMjVLJxNx`
* Message: `SomeMsg`
* Signature from Electrum: `IBimiACbzHLFhs7X82lc4jZc9+EHbVcBTu8OGiIstjyUWiWQNdh3F3A3AdOOBMMn+965EjY6PVstl56g62Wa7vE=`

First we import
```python
import base64
from bit.utils import int_to_varint
from bit.crypto import sha256
```
Given your signature from Electrum
```python
electrum_sig = "IBimiACbzHLFhs7X82lc4jZc9+EHbVcBTu8OGiIstjyUWiWQNdh3F3A3AdOOBMMn+965EjY6PVstl56g62Wa7vE="
```

We convert it to hex and keep only the R and S values appended in `sig`:
```python
sig = base64.b64decode(electrum_sig)
# Remove the first byte which is an Electrum thing:
sig = sig[1:]
```

This hex-encoded signature consists of `R|S` and each `R` and `S` values are 32 bytes.

Lastly we must reconstruct the message:
Lets say the message was `SomeMsg`:
```python
message = "SomeMsg"
m = "\x18Bitcoin Signed Message:\n" + int_to_varint( len(message) ).decode('utf-8') + message
mhash = sha256(m.encode('utf-8'))
```

Now we can combine all that to verify the signature. We just rewrite Ofek's function slightly:
```python
from bit.format import public_key_to_address
from coincurve import PublicKey
from coincurve.ecdsa import der_to_cdata, serialize_compact
from coincurve.utils import int_to_bytes

def verify(sig_compact, message, address):
    for rec_id in (0, 1, 2, 3):
        serialized_recoverable_sig = sig_compact + int_to_bytes(rec_id)
        try:
            pk = PublicKey.from_signature_and_message(serialized_recoverable_sig, message)
        except:
            return False
        if (
            public_key_to_address(pk.format()) == address
            or public_key_to_address(pk.format(compressed=False)) == address
        ):
            return True
    return False
```

Lastly we make use of this new `verify` function:
```python
verify(sig, mhash, "13bq7o1ybfnG83wSfyinuWvLrVMjVLJxNx")
> True
```


[1]: https://bitcoin.stackexchange.com/questions/77324/how-are-bitcoin-signed-messages-generated
[2]: https://bitcoin.stackexchange.com/questions/77191/what-is-the-maximum-size-of-a-der-encoded-ecdsa-signature

**Comment by teran-mckinney** [comment]
Awesome work! Tons of great info here. Will have to look over this later. Thank you!

**Comment by nirmalthacker** [comment]
@bjarnemagnussen 🎆  thanks this works!  Also, thanks for elaborating on the formats and requirements. This was less straightforward than I assumed and lots to learn! Couple of questions/observations:

1. This doesnt work for Segwit (bech32) addresses. Is this because of Issue #82 
2. What was the first byte that electrum prepends that needed to be snipped out. I wonder if there's a way to make this generic enough to work across different wallet programs. Any ideas?

**Comment by nirmalthacker** [comment]
@bjarnemagnussen amazing! Thanks! Closing this issue given its pretty much resolved from my end
