### ISSUE TITLE
question

### ISSUE THREAD

**Issue by su314ka** [ofek/bit#88]
Hi,

It`s possible to convert a publickey to hash160(publickey) using bit?
Example: https://learnmeabitcoin.com/glossary/public-key-hash160
Thanks!

**Comment by ofek** [comment]
https://github.com/ofek/bit/blob/b287ee9ad2253b3a1a86b8afa45eac8c3887d1d5/bit/crypto.py#L18-L19

**Comment by su314ka** [comment]
I tried, but I get the public key like: b'\x03[{\x08\x9e\xf3\x90|\xa5`\x18|\x92\x18\xaei\xc1\xccl\x7f'

**Comment by ofek** [comment]
Do you want hex?

**Comment by su314ka** [comment]
Yes. Would be great.

**Comment by ofek** [comment]
https://github.com/ofek/bit/blob/b287ee9ad2253b3a1a86b8afa45eac8c3887d1d5/bit/utils.py#L20-L22

**Comment by su314ka** [comment]
Perfect. Thank you.

**Comment by ofek** [comment]
Anytime!
