### ISSUE TITLE
Lookup existing transaction by Transaction ID or Hash ID

### ISSUE THREAD

**Issue by ncbentley** [ofek/bit#89]
Maybe I'm missing something simple, but the ability to lookup a transaction using the tx id or hash id would be super helpful.

**Comment by bjarnemagnussen** [comment]
It has been added with commit 81ce3412438b83b1d3fe0cb2e29d95b9316c237b.

You can call it with
```
from bit.network import NetworkAPI
tx = NetworkAPI.get_transaction_by_id("txid")
```

See also `help(NetworkAPI.get_transaction_by_id)`.
