### ISSUE TITLE
Add support for Bitcoin Cash

### ISSUE THREAD

**Issue by gappleto97** [ofek/bit#9]

**Comment by ofek** [comment]
Sorry @gappleto97 but I do not want to support that. I just don't agree with their stance and distrust the team/development of it w.r.t. security.

Though, if a PR were submitted I would reconsider :)

**Comment by teran-mckinney** [comment]
If bit supports bip143 this should pretty much just be a sighash change. I'm going to take a peek.

**Comment by teran-mckinney** [comment]
I can't see an easy way for Bitcoin and BitcoinCash to coexist in bit without a significant rewrite of the codebase. I don't think it makes a ton of sense to do that, especially as Bitcoin and BitcoinCash will likely diverge more and more in time.

As such, I've forked @bjarnemagnussen's fork's segwit branch as the basis of https://github.com/sporestack/bitcash

I want to have the libraries as compatible as possible from a usage standpoint unless it's absolutely necessary to diverge. Should be very easy to write software that uses either.

**Comment by teran-mckinney** [comment]
bitcash is working now. If this sounds like a good solution to both of you, I believe this can be closed out.
