### ISSUE TITLE
Possibly a bug with x_to_y function

### ISSUE THREAD

**Issue by olalonde** [ofek/bit#96]
There appears to be a bug either in this library or [fastecdsa](https://github.com/AntonKueltz/fastecdsa) one:

<img width="1112" alt="Screenshot 2020-01-25 00 58 42" src="https://user-images.githubusercontent.com/416585/73117027-e1953c00-3f0d-11ea-9cf7-ac09eefa9ef0.png">

```python
from fastecdsa.curve import secp256k1
from fastecdsa.point import Point
from bit.curve import x_to_y # get y given x on bitcoin curve

x = 14899878097
y = x_to_y(x, 0)
Point(x, y, curve=secp256k1)
# gives error: point doesn't exist on curve


x = 14899878097 + 1
y = x_to_y(x, 0)
Point(x, y, curve=secp256k1)

# works!
```

Unfortunately, I'm not familiar enough to verify myself.

**Comment by olalonde** [comment]
I believe it's a bug in fastecdsa (https://github.com/AntonKueltz/fastecdsa/issues/48), feel free to close.

**Comment by ofek** [comment]
Good debugging, thanks!

**Comment by teran-mckinney** [comment]
Yeah, nice job on this! Looking forward to seeing if this is a bug and what the cause is. Certainly relevant here.
